// Package v5 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.0 DO NOT EDIT.
package v5

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	BearerScopes = "bearer.Scopes"
)

// Defines values for MachineOwnResponseOwnType.
const (
	Root MachineOwnResponseOwnType = "Root"
	User MachineOwnResponseOwnType = "User"
)

// MachineOwnErrorResponse Schema definition for Own Error Response
type MachineOwnErrorResponse struct {
	Message string `json:"message"`
	Status  int    `json:"status"`
}

// MachineOwnRequest Schema definition for Own Request
type MachineOwnRequest struct {
	Difficulty *int `json:"difficulty,omitempty"`

	// Flag MD5 hash of the machine flag
	Flag string `json:"flag"`

	// Id The machine ID
	Id int `json:"id"`
}

// MachineOwnResponse Schema definition for Machine Own Response
type MachineOwnResponse struct {
	BloodPoints      int                       `json:"blood_points"`
	BloodTaken       int                       `json:"blood_taken"`
	Id               int                       `json:"id"`
	IsStartingPoint  bool                      `json:"is_starting_point"`
	LeagueRank       *RankUpdate               `json:"league_rank,omitempty"`
	MachineCompleted bool                      `json:"machine_completed"`
	MachinePwned     bool                      `json:"machine_pwned"`
	MachineState     string                    `json:"machine_state"`
	Message          string                    `json:"message"`
	OwnType          MachineOwnResponseOwnType `json:"own_type"`
	Points           int                       `json:"points"`
	Status           int                       `json:"status"`
	Success          bool                      `json:"success"`
	UserRank         *RankUpdate               `json:"user_rank,omitempty"`
}

// MachineOwnResponseOwnType defines model for MachineOwnResponse.OwnType.
type MachineOwnResponseOwnType string

// NewRank defines model for NewRank.
type NewRank struct {
	Id   *int    `json:"id,omitempty"`
	Text *string `json:"text"`
}

// RankUpdate defines model for RankUpdate.
type RankUpdate struct {
	Changed *bool    `json:"changed,omitempty"`
	NewRank *NewRank `json:"newRank,omitempty"`
}

// MachineOwn400Response Schema definition for Own Error Response
type MachineOwn400Response = MachineOwnErrorResponse

// PostMachineOwnJSONRequestBody defines body for PostMachineOwn for application/json ContentType.
type PostMachineOwnJSONRequestBody = MachineOwnRequest

// PostMachineOwnFormdataRequestBody defines body for PostMachineOwn for application/x-www-form-urlencoded ContentType.
type PostMachineOwnFormdataRequestBody = MachineOwnRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostMachineOwnWithBody request with any body
	PostMachineOwnWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostMachineOwn(ctx context.Context, body PostMachineOwnJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostMachineOwnWithFormdataBody(ctx context.Context, body PostMachineOwnFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostMachineOwnWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostMachineOwnRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostMachineOwn(ctx context.Context, body PostMachineOwnJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostMachineOwnRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostMachineOwnWithFormdataBody(ctx context.Context, body PostMachineOwnFormdataRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostMachineOwnRequestWithFormdataBody(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostMachineOwnRequest calls the generic PostMachineOwn builder with application/json body
func NewPostMachineOwnRequest(server string, body PostMachineOwnJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostMachineOwnRequestWithBody(server, "application/json", bodyReader)
}

// NewPostMachineOwnRequestWithFormdataBody calls the generic PostMachineOwn builder with application/x-www-form-urlencoded body
func NewPostMachineOwnRequestWithFormdataBody(server string, body PostMachineOwnFormdataRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	bodyStr, err := runtime.MarshalForm(body, nil)
	if err != nil {
		return nil, err
	}
	bodyReader = strings.NewReader(bodyStr.Encode())
	return NewPostMachineOwnRequestWithBody(server, "application/x-www-form-urlencoded", bodyReader)
}

// NewPostMachineOwnRequestWithBody generates requests for PostMachineOwn with any type of body
func NewPostMachineOwnRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/machine/own")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostMachineOwnWithBodyWithResponse request with any body
	PostMachineOwnWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostMachineOwnResponse, error)

	PostMachineOwnWithResponse(ctx context.Context, body PostMachineOwnJSONRequestBody, reqEditors ...RequestEditorFn) (*PostMachineOwnResponse, error)

	PostMachineOwnWithFormdataBodyWithResponse(ctx context.Context, body PostMachineOwnFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostMachineOwnResponse, error)
}

type PostMachineOwnResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MachineOwnResponse
	JSON400      *MachineOwn400Response
}

// Status returns HTTPResponse.Status
func (r PostMachineOwnResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostMachineOwnResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostMachineOwnWithBodyWithResponse request with arbitrary body returning *PostMachineOwnResponse
func (c *ClientWithResponses) PostMachineOwnWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostMachineOwnResponse, error) {
	rsp, err := c.PostMachineOwnWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostMachineOwnResponse(rsp)
}

func (c *ClientWithResponses) PostMachineOwnWithResponse(ctx context.Context, body PostMachineOwnJSONRequestBody, reqEditors ...RequestEditorFn) (*PostMachineOwnResponse, error) {
	rsp, err := c.PostMachineOwn(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostMachineOwnResponse(rsp)
}

func (c *ClientWithResponses) PostMachineOwnWithFormdataBodyWithResponse(ctx context.Context, body PostMachineOwnFormdataRequestBody, reqEditors ...RequestEditorFn) (*PostMachineOwnResponse, error) {
	rsp, err := c.PostMachineOwnWithFormdataBody(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostMachineOwnResponse(rsp)
}

// ParsePostMachineOwnResponse parses an HTTP response from a PostMachineOwnWithResponse call
func ParsePostMachineOwnResponse(rsp *http.Response) (*PostMachineOwnResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostMachineOwnResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MachineOwnResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest MachineOwn400Response
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	}

	return response, nil
}
